### ISSUE TITLE
I'm getting a crash on moving from one tab to another when the width of navBar's content is less then the categoryView's width.

### ISSUE THREAD

**Issue by GoluKumar1** [bestiosdeveloper/PKCategoryView#1]
I'm attaching the screen shot of my ViewController with the scenario.
Help will be appreciated.
![IMG-2116](https://user-images.githubusercontent.com/54105605/63019000-d5fe0d80-beb7-11e9-9a28-b3c7dca66e9d.PNG)

**Comment by bestiosdeveloper** [comment]
@GoluKumar1 Sure, let me check the issue. I'll get back to you very soon.

**Comment by pramod-kumar-ios** [comment]
@GoluKumar1  It has been fixed now in version 0.1.3
