### ISSUE TITLE
When there are only 3 tabs , then tabs moves to right side.I am using it on iPhone7

### ISSUE THREAD

**Issue by rakshit104** [bestiosdeveloper/PKCategoryView#2]
![tapRightSide](https://user-images.githubusercontent.com/31876736/63319600-4d102780-c338-11e9-9783-5ea3aae388cf.jpg)

**Comment by pramod-kumar-ios** [comment]
@rakshit104 This one is also fixed in V 0.1.3
Update your pod files.
Happy Coding :)
